require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
LineLength:
  Max: 100
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/*'
    - '*.gemspec'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/lite/base_validator_spec.rb'
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
